/* ===================================================================
   Quran & Me — Surah dataset
   Compiled from public-domain Islamic scholarship. Facts (names, verse
   counts, Meccan/Medinan classification) are consistent across Sunni and
   Shia sources. Historical context / "story" notes draw where possible
   on Shia exegesis (Tafsir al-Mizan by Allamah Tabataba'i, al-islam.org,
   wikishia.net) and are marked with a "shia" field when there is a
   distinct Shia narrative worth noting. "virtue" notes traditionally
   cited benefits/occasions for reciting a surah — these come from
   hadith of varying strength across sources; treat them as devotional
   tradition, not obligation. See references.js / the References screen
   in the app for the full source list.
   =================================================================== */

const SURAHS = [
{n:1,ar:"الفاتحة",tr:"Al-Fatihah",en:"The Opening",place:"Meccan",verses:7,
 summary:"The seven-verse preface to the Quran, recited in every unit of the daily prayer. It praises God as Lord of the worlds, the Merciful, and Master of the Day of Judgment, then asks to be guided on the 'straight path' — the path of those God has blessed, not those who earned His anger or went astray.",
 shia:"Shia tradition holds that 'those who earned Your anger' and 'those who went astray' refer to two groups who deviated from the guidance given to them, and reads 'the straight path' as the path embodied by the Prophet and his rightly-guided family (Ahl al-Bayt). Al-Fatihah is called Umm al-Kitab, 'the mother of the Book.'",
 themes:["Prayer","Guidance","God's mercy"],
 virtue:"Obligatory in every unit of every prayer — no prayer is valid without it. Often called 'the greatest surah in the Quran' in hadith."},
{n:2,ar:"البقرة",tr:"Al-Baqarah",en:"The Cow",place:"Medinan",verses:286,
 summary:"The longest surah, revealed over most of the Medinan period. It opens with the nature of belief and disbelief, retells the Israelites' story of the sacrificed cow, covers the change of the prayer direction (qiblah) from Jerusalem to Mecca, and lays out core laws: fasting, pilgrimage, retaliation, inheritance, usury, and the famous Ayat al-Kursi (the Throne Verse, 2:255) on God's sustaining power.",
 shia:"Verse 2:207, describing a man who 'sells himself seeking God's pleasure,' is widely reported in Shia sources (and some Sunni ones) as revealed about Imam Ali sleeping in the Prophet's bed the night of the migration (Laylat al-Mabit), risking his life so the Prophet could escape Mecca safely.",
 themes:["Law","Faith vs. disbelief","Ayat al-Kursi","Covenant"],
 virtue:"The Prophet said reciting it brings blessing to a home and repels harm; its last two verses (2:285-286) are widely recited at night for protection."},
{n:3,ar:"آل عمران",tr:"Aal-e-Imran",en:"The Family of Imran",place:"Medinan",verses:200,
 summary:"Named for the family of Imran (father of Mary), this surah discusses the birth of Mary and Jesus, debates with a Christian delegation from Najran, and reflects on the battles of Badr and Uhud, drawing lessons about steadfastness, trust in God, and the trials of the early Muslim community.",
 shia:"Verse 3:61, the 'Verse of Mubahala' (mutual invocation of a curse), is central to Shia belief: when Christian debaters would not accept the truth about Jesus, the Prophet brought only Ali, Fatimah, Hasan and Husayn to represent 'our sons, our women, and ourselves' — cited as proof of the exceptional rank of the Ahl al-Bayt.",
 themes:["Mary & Jesus","Mubahala","Trials of faith","Steadfastness"]},
{n:4,ar:"النساء",tr:"An-Nisa",en:"The Women",place:"Medinan",verses:176,
 summary:"A detailed surah of social legislation: orphans' rights, marriage, inheritance shares, treatment of women, and justice in testimony and leadership, revealed as the Medinan community grew and needed a legal framework, alongside guidance following the Battle of Uhud.",
 shia:"Verse 4:59, commanding obedience to God, the Messenger, and 'those in authority among you' (ulu al-amr), is read in Shia theology as referring specifically to the infallible Imams from the Prophet's family, since the verse implies an authority whose obedience is unconditional and therefore free from error.",
 themes:["Women's rights","Orphans","Inheritance","Justice"]},
{n:5,ar:"المائدة",tr:"Al-Ma'idah",en:"The Table Spread",place:"Medinan",verses:120,
 summary:"One of the last surahs revealed, dealing with dietary law, contracts, the request of Jesus's disciples for a table of food from heaven as a sign, and warnings to the People of the Book — closing the era of legislation shortly before the Prophet's death.",
 shia:"Two verses here are pillars of Shia doctrine. 5:55, 'Ayat al-Wilayah,' — 'Your guardian (wali) is only God, His Messenger, and those who believe, who establish prayer and give charity while bowing' — is widely reported as revealed when Ali gave his ring in charity while bowing in prayer. 5:3, revealed at Ghadir Khumm, declares 'today I have perfected your religion' immediately after (in the Shia account) the Prophet appointed Ali as his successor.",
 themes:["Contracts","Food law","Wilayah","Completion of religion"]},
{n:6,ar:"الأنعام",tr:"Al-An'am",en:"The Cattle",place:"Meccan",verses:165,
 summary:"A sweeping Meccan argument for God's oneness against idolatry, using the design of the cosmos, the story of Abraham questioning star- and idol-worship, and superstitions about cattle, to call the Quraysh back to pure monotheism.",
 themes:["Tawhid","Abraham","Idolatry"],
 virtue:"Traditionally said to have been revealed all at once, accompanied (in narrations) by a great number of angels — reflecting its weight as a sustained argument for monotheism."},
{n:7,ar:"الأعراف",tr:"Al-A'raf",en:"The Heights",place:"Meccan",verses:206,
 summary:"Recounts the stories of earlier prophets — Adam and Iblis, Noah, Hud, Salih, Lot, Shu'ayb, and Moses versus Pharaoh — as warnings to Mecca, and describes 'the Heights' (al-A'raf), a barrier between Paradise and Hell where people of balanced deeds wait.",
 themes:["Prophets' stories","Adam & Iblis","The Heights"]},
{n:8,ar:"الأنفال",tr:"Al-Anfal",en:"The Spoils of War",place:"Medinan",verses:75,
 summary:"Revealed after the Battle of Badr, the first major military victory of the Muslims, addressing the division of war gains, the etiquette of battle, and the small, ill-equipped believing community's reliance on God against a larger force.",
 themes:["Battle of Badr","Trust in God","Justice in war"]},
{n:9,ar:"التوبة",tr:"At-Tawbah",en:"The Repentance",place:"Medinan",verses:129,
 summary:"The only surah without the opening 'Bismillah,' revealed near the end of the Prophet's life. It addresses treaty-breaking by some Meccan tribes, hypocrisy within Medina, and the expedition to Tabuk, while opening the door of repentance to those who had failed to join it.",
 themes:["Repentance","Treaties","Hypocrisy"]},
{n:10,ar:"يونس",tr:"Yunus",en:"Jonah",place:"Meccan",verses:109,
 summary:"Named after the prophet Jonah, whose people uniquely repented and were spared destruction. The surah reassures the Prophet that rejection is not proof of failure, contrasting Jonah's people with earlier nations destroyed for persistent denial.",
 themes:["Jonah","Repentance","Patience with rejection"]},
{n:11,ar:"هود",tr:"Hud",en:"Hud",place:"Meccan",verses:123,
 summary:"A surah of successive prophetic stories — Noah, Hud, Salih, Abraham, Lot, Shu'ayb, and Moses — each people destroyed after rejecting their messenger, used as a sober warning to the Quraysh; the Prophet reportedly said this surah 'turned my hair grey.'",
 themes:["Prophets' stories","Consequences of denial","Steadfastness"]},
{n:12,ar:"يوسف",tr:"Yusuf",en:"Joseph",place:"Meccan",verses:111,
 summary:"Called 'the best of stories' in its own opening verse, this is the only surah telling one continuous narrative: Joseph's betrayal by his brothers, slavery in Egypt, the temptation by Potiphar's wife, imprisonment, rise to power, and eventual reunion with his family — a story of patience, forgiveness, and divine planning.",
 themes:["Joseph","Patience","Forgiveness","Divine planning"],
 virtue:"Recommended reading for anyone facing family betrayal, jealousy, or a long wait for a difficult situation to resolve — the entire arc models patient trust in God's plan."},
{n:13,ar:"الرعد",tr:"Ar-Ra'd",en:"The Thunder",place:"Meccan",verses:43,
 summary:"Describes thunder and lightning as signs glorifying God, affirms that hearts find rest 'in the remembrance of God,' and contrasts the fate of those who keep their covenant with God against those who break it.",
 themes:["Signs in nature","Remembrance of God","Covenant"]},
{n:14,ar:"ابراهيم",tr:"Ibrahim",en:"Abraham",place:"Meccan",verses:52,
 summary:"Centers on Abraham's prayer for Mecca and his descendants, the imagery of a 'good word' as a firmly rooted tree, and warnings about ingratitude, addressed to a Mecca that enjoyed security while rejecting its own prophet.",
 themes:["Abraham's prayer","Gratitude","The good word"]},
{n:15,ar:"الحجر",tr:"Al-Hijr",en:"The Rocky Tract",place:"Meccan",verses:99,
 summary:"Named for the rock-carved dwellings of the Thamud people, it recounts the creation of Adam, Iblis's refusal to prostrate, the destruction of Lot's people and Thamud, and affirms God's promise to preserve the Quran from corruption (15:9).",
 themes:["Preservation of the Quran","Adam & Iblis","Thamud"]},
{n:16,ar:"النحل",tr:"An-Nahl",en:"The Bee",place:"Meccan",verses:128,
 summary:"Also called 'Surah of the Blessings,' it catalogs God's favors in nature — rain, cattle, honeybees, the sea — as evidence for gratitude and monotheism, and closes with guidance on calling to God 'with wisdom and good instruction.'",
 shia:"Verse 16:43, 'ask the people of remembrance (ahl al-dhikr) if you do not know,' is understood in Shia tafsir as instructing believers to refer religious questions to the Prophet's household and their true scholarly heirs.",
 themes:["God's favors","Gratitude","Wise communication"]},
{n:17,ar:"الإسراء",tr:"Al-Isra",en:"The Night Journey",place:"Meccan",verses:111,
 summary:"Opens with the Prophet's night journey from Mecca's sacred mosque to Jerusalem's al-Aqsa Mosque, then continues with ethical commandments — kindness to parents, honesty, humility — and reflections on the Israelites' history.",
 themes:["Night Journey","Kindness to parents","Ethics"]},
{n:18,ar:"الكهف",tr:"Al-Kahf",en:"The Cave",place:"Meccan",verses:110,
 summary:"Contains three parables of testing: the Companions of the Cave (youths who fled persecution and slept for centuries), a man whose wealth blinded him to gratitude, and Moses's journey with the mysterious servant Khidr, plus the story of Dhul-Qarnayn. Widely recommended for Friday recitation for its light and protection from trial.",
 themes:["Testing of faith","Wealth & gratitude","Hidden wisdom"],
 virtue:"Widely recommended for recitation every Friday; hadith describe it as a light between two Fridays and protection from the trial (fitnah) of the Dajjal."},
{n:19,ar:"مريم",tr:"Maryam",en:"Mary",place:"Meccan",verses:98,
 summary:"Named for Mary, mother of Jesus — the only surah named after a woman — it narrates the births of John (Yahya) to Zechariah and Jesus to Mary in tender detail, alongside Abraham's gentle appeal to his idol-worshipping father.",
 themes:["Mary","Miraculous births","Gentle da'wah"]},
{n:20,ar:"طه",tr:"Ta-Ha",en:"Ta-Ha",place:"Meccan",verses:135,
 summary:"Named after its opening letters, it retells Moses's calling at the burning bush, his mission to Pharaoh, the parting of the sea, and the episode of the golden calf, framed as comfort and instruction for the Prophet facing his own rejection.",
 themes:["Moses","Divine calling","Comfort in rejection"]},
{n:21,ar:"الأنبياء",tr:"Al-Anbiya",en:"The Prophets",place:"Meccan",verses:112,
 summary:"A rapid survey of many prophets — Abraham, Lot, Noah, David, Solomon, Job, Jonah, Zechariah, and others — emphasizing that all messengers taught the same core message: 'There is no god but Me, so worship Me' (21:25).",
 themes:["Unity of prophets' message","Tawhid"]},
{n:22,ar:"الحج",tr:"Al-Hajj",en:"The Pilgrimage",place:"Medinan",verses:78,
 summary:"Covers the rites, history, and spiritual purpose of the Hajj pilgrimage to the Kaaba built by Abraham and Ishmael, along with permission for the wronged community to defend itself, and vivid depictions of the Day of Judgment.",
 themes:["Hajj rites","Self-defense","Day of Judgment"]},
{n:23,ar:"المؤمنون",tr:"Al-Mu'minun",en:"The Believers",place:"Meccan",verses:118,
 summary:"Opens by listing the qualities of successful believers — humility in prayer, honesty, chastity, trustworthiness — then traces the stages of human creation in the womb as a sign of God's power to resurrect.",
 themes:["Qualities of believers","Human creation","Resurrection"]},
{n:24,ar:"النور",tr:"An-Nur",en:"The Light",place:"Medinan",verses:64,
 summary:"Legislates modesty, guards against slander, and contains the celebrated 'Verse of Light' (24:35) comparing God's guidance to a lamp in a niche — 'light upon light' — alongside rules protecting the dignity and privacy of the household.",
 themes:["Modesty","Slander","Verse of Light"]},
{n:25,ar:"الفرقان",tr:"Al-Furqan",en:"The Criterion",place:"Meccan",verses:77,
 summary:"'Al-Furqan' means the standard that distinguishes truth from falsehood. The surah answers Meccan objections to the Prophet's humanity, describes the qualities of 'the servants of the Merciful,' and warns of the regret of those who followed the wrong companions.",
 themes:["Truth vs. falsehood","Servants of the Merciful"]},
{n:26,ar:"الشعراء",tr:"Ash-Shu'ara",en:"The Poets",place:"Meccan",verses:227,
 summary:"Retells Moses, Abraham, Noah, Hud, Salih, Lot, and Shu'ayb each confronting a people who rejected them, then closes by distinguishing true revelation from poetry, defending the Quran against accusations that the Prophet was merely a poet.",
 themes:["Prophets' stories","Quran vs. poetry"]},
{n:27,ar:"النمل",tr:"An-Naml",en:"The Ants",place:"Meccan",verses:93,
 summary:"Named for the ant who warns her colony of Solomon's approaching army, this surah also tells of the hoopoe bird bringing news of the Queen of Sheba (Bilqis) and her eventual submission to God through Solomon.",
 themes:["Solomon","Queen of Sheba","Wisdom in creation"]},
{n:28,ar:"القصص",tr:"Al-Qasas",en:"The Narration",place:"Meccan",verses:88,
 summary:"Tells the fuller story of Moses — his birth under Pharaoh's persecution, upbringing, flight to Midian, marriage, and calling — paralleling the Prophet's own persecution and eventual return to a hostile Mecca.",
 themes:["Moses","Exile & return","Divine protection"]},
{n:29,ar:"العنكبوت",tr:"Al-Ankabut",en:"The Spider",place:"Meccan",verses:69,
 summary:"Opens by asking whether people think they will be left untested merely for professing faith, then compares those who rely on protectors besides God to a spider's fragile web — 'the frailest of houses' — while retelling Noah, Abraham, and Lot.",
 themes:["Trials of faith","False reliance"]},
{n:30,ar:"الروم",tr:"Ar-Rum",en:"The Romans",place:"Meccan",verses:60,
 summary:"Opens with a striking prophecy: the Byzantine Romans, recently defeated by the Persians, would be victorious again within a few years — fulfilled after the surah's revelation — offered as evidence the Quran's message was from God.",
 themes:["Prophecy fulfilled","Signs of truth"]},
{n:31,ar:"لقمان",tr:"Luqman",en:"Luqman",place:"Meccan",verses:34,
 summary:"Centers on the wisdom Luqman gave his son: warnings against idolatry ('associating partners with God is a great injustice'), honoring parents, humility in walking and speech, and steadfastness in prayer.",
 themes:["Parental wisdom","Humility","Tawhid"],
 virtue:"A favorite surah for teaching children core values — its verses of fatherly advice are widely memorized as a starting point for family Islamic education."},
{n:32,ar:"السجدة",tr:"As-Sajdah",en:"The Prostration",place:"Meccan",verses:30,
 summary:"Describes believers whose 'sides forsake their beds' to pray at night in longing for God, and contains a prostration verse (32:15) recited by Muslims worldwide during recitation of the Quran.",
 themes:["Night prayer","Prostration"],
 virtue:"Traditionally recited in the Fajr prayer on Fridays, paired with Surah Al-Insan."},
{n:33,ar:"الأحزاب",tr:"Al-Ahzab",en:"The Combined Forces",place:"Medinan",verses:73,
 summary:"Named for the confederate tribes ('Ahzab') who besieged Medina in the Battle of the Trench, it also legislates on adoption, the Prophet's household, and the etiquette of addressing the Prophet's wives.",
 shia:"Verse 33:33, the 'Verse of Purification' (Ayat al-Tathir) — 'God only wishes to remove impurity from you, O People of the House, and purify you with a thorough purification' — is central to Shia belief in the infallibility (ismah) of the Ahl al-Bayt. Hadith in both Sunni and Shia collections describe the Prophet gathering Ali, Fatimah, Hasan, and Husayn under his cloak (the event of the Kisa) when this verse was revealed.",
 themes:["Battle of the Trench","Ayat al-Tathir","Household laws"]},
{n:34,ar:"سبأ",tr:"Saba",en:"Sheba",place:"Meccan",verses:54,
 summary:"Tells of the kingdom of Sheba, whose prosperous dams and gardens were destroyed by a great flood after ingratitude, alongside the story of David and Solomon's God-given blessings, as a lesson on gratitude versus arrogance.",
 themes:["Gratitude vs. arrogance","David & Solomon"]},
{n:35,ar:"فاطر",tr:"Fatir",en:"Originator",place:"Meccan",verses:45,
 summary:"Opens by describing God as 'Originator of the heavens and earth,' who made angels with wings, and reflects on the diversity of creation — mountains, fruits, people — as proof of a wise Creator behind a world of contrasts.",
 themes:["Creation","Angels","Diversity as a sign"]},
{n:36,ar:"يس",tr:"Ya-Sin",en:"Ya-Sin",place:"Meccan",verses:83,
 summary:"Often called 'the heart of the Quran,' it tells the parable of a town that rejected three messengers except for one believing man who ran to defend them, and vividly affirms resurrection through the imagery of dead land brought to life by rain. Widely recited for the dying and the deceased.",
 themes:["Resurrection","A believer's courage"],
 virtue:"Called 'the heart of the Quran' in a well-known hadith; widely recited for the dying and for the deceased, and recommended reading on Friday nights."},
{n:37,ar:"الصافات",tr:"As-Saffat",en:"Those Ranged in Ranks",place:"Meccan",verses:182,
 summary:"Describes angels standing in ranks, then retells Noah, Abraham's willingness to sacrifice his son, Isaac, Moses and Aaron, Elijah, Lot, and Jonah, as a chain of prophets who trusted God completely.",
 themes:["Angels","Abraham's sacrifice","Trust in God"]},
{n:38,ar:"ص",tr:"Sad",en:"Sad",place:"Meccan",verses:88,
 summary:"Addresses Meccan arrogance and disunity, then recounts David's justice and repentance, Solomon's devotion, and Job's patient endurance of illness and loss, closing with Iblis's refusal to bow to Adam.",
 themes:["David","Job's patience","Repentance"]},
{n:39,ar:"الزمر",tr:"Az-Zumar",en:"The Troops",place:"Meccan",verses:75,
 summary:"Urges sincere devotion to God alone, contrasts the anxious polytheist with the believer at peace, and describes people entering Paradise and Hell 'in troops' (zumar) on the Day of Judgment.",
 themes:["Sincerity","Judgment Day"]},
{n:40,ar:"غافر",tr:"Ghafir",en:"The Forgiver",place:"Meccan",verses:85,
 summary:"Also called 'Al-Mu'min' for the secret believer in Pharaoh's court who defended Moses at the risk of his life, this surah opens with God's names as Forgiver and Severe in punishment, balancing mercy with justice.",
 themes:["Divine forgiveness","Courage of a secret believer"]},
{n:41,ar:"فصلت",tr:"Fussilat",en:"Explained in Detail",place:"Meccan",verses:54,
 summary:"Describes the Quran as a book 'whose verses are explained in detail,' invites reflection on the cosmos as a sign, and pictures a person's own skin testifying against them on Judgment Day for deeds done in secret.",
 themes:["Signs in the cosmos","Accountability"]},
{n:42,ar:"الشورى",tr:"Ash-Shura",en:"The Consultation",place:"Meccan",verses:53,
 summary:"Instructs believers to conduct their affairs 'by mutual consultation,' affirms that revelation to Muhammad continues the same message sent to Noah, Abraham, Moses, and Jesus, and reassures the Prophet that guidance, not compulsion, is his task.",
 shia:"Verse 42:23, where the Prophet is told to say 'I ask no reward for this except love for [my] near relatives,' is read in Shia tradition as establishing love and loyalty to the Ahl al-Bayt as a religious obligation, not merely family affection.",
 themes:["Consultation (shura)","Love of the Prophet's family"]},
{n:43,ar:"الزخرف",tr:"Az-Zukhruf",en:"The Gold Adornments",place:"Meccan",verses:89,
 summary:"Questions why the Quraysh valued gold ornaments and worldly rank over guidance, revisits Abraham's rejection of his father's idols and Moses versus Pharaoh, and stresses that nearness to God is measured by piety, not wealth.",
 themes:["Wealth vs. piety","Abraham"]},
{n:44,ar:"الدخان",tr:"Ad-Dukhan",en:"The Smoke",place:"Meccan",verses:59,
 summary:"Describes a 'clear smoke' as a coming sign of punishment for persistent deniers, recalls Pharaoh's drowning after oppressing the Israelites, and contrasts the tree of Zaqqum in Hell with the gardens prepared for the righteous.",
 themes:["Warning sign","Pharaoh's downfall"]},
{n:45,ar:"الجاثية",tr:"Al-Jathiyah",en:"The Kneeling",place:"Meccan",verses:37,
 summary:"Describes every nation 'kneeling' before God on Judgment Day to be judged from its own record, warning against treating personal desire as one's god and dismissing the Hereafter as mere chance.",
 themes:["Judgment Day","Following desire"]},
{n:46,ar:"الأحقاف",tr:"Al-Ahqaf",en:"The Sand Dunes",place:"Meccan",verses:35,
 summary:"Named for the sand-dune region of the 'Ad people destroyed by a violent wind, it also records a jinn delegation secretly listening to the Quran and returning to warn their own people to believe.",
 themes:["'Ad people","Jinn believing"]},
{n:47,ar:"محمد",tr:"Muhammad",en:"Muhammad",place:"Medinan",verses:38,
 summary:"Also called 'Al-Qital' (Combat), it addresses believers permitted to fight in self-defense against those who barred them from Mecca, contrasting the fate of those who obstruct God's path with those who strive for it.",
 themes:["Self-defense","Striving for faith"]},
{n:48,ar:"الفتح",tr:"Al-Fath",en:"The Victory",place:"Medinan",verses:29,
 summary:"Revealed after the Treaty of Hudaybiyyah — outwardly a setback but described here as 'a clear victory' — it describes the pledge of allegiance under a tree (Bay'at al-Ridwan) and closes with a description of the Prophet's companions.",
 themes:["Treaty of Hudaybiyyah","Hidden victory"]},
{n:49,ar:"الحجرات",tr:"Al-Hujurat",en:"The Chambers",place:"Medinan",verses:18,
 summary:"Named for the private chambers of the Prophet's household, it teaches etiquette: verifying news before acting on it, not mocking or backbiting others, and that the noblest before God is the most God-conscious, 'not the most tribal.'",
 themes:["Social etiquette","Verifying news","Equality"],
 virtue:"A go-to surah for practical guidance on gossip, backbiting, and verifying information before spreading it — highly relevant to conduct in any era, including online."},
{n:50,ar:"ق",tr:"Qaf",en:"Qaf",place:"Meccan",verses:45,
 summary:"Answers Meccan disbelief in resurrection by pointing to the revival of dead earth by rain, and describes two recording angels seated on each shoulder, and God being 'closer to him than his jugular vein' (50:16).",
 themes:["Resurrection","Recording angels","Nearness of God"]},
{n:51,ar:"الذاريات",tr:"Adh-Dhariyat",en:"The Scattering Winds",place:"Meccan",verses:60,
 summary:"Opens swearing by winds that scatter dust, affirming the Day of Judgment is certain, then retells the angels' visit to Abraham announcing Isaac's birth and warning of Lot's people's destruction.",
 themes:["Certainty of Judgment","Abraham's guests"]},
{n:52,ar:"الطور",tr:"At-Tur",en:"The Mount",place:"Meccan",verses:49,
 summary:"Swears by Mount Sinai and the inscribed scripture to affirm the coming punishment of deniers, rebuts the accusation that the Quran was fabricated by the Prophet, and challenges skeptics to produce anything like it.",
 themes:["Authenticity of the Quran","Challenge to skeptics"]},
{n:53,ar:"النجم",tr:"An-Najm",en:"The Star",place:"Meccan",verses:62,
 summary:"Defends the authenticity of the Prophet's revelation and his night journey vision, states that no soul bears another's burden, and ends with a prostration verse affirming God alone as worthy of worship.",
 themes:["Revelation's authenticity","Personal accountability"]},
{n:54,ar:"القمر",tr:"Al-Qamar",en:"The Moon",place:"Meccan",verses:55,
 summary:"Opens referencing the splitting of the moon as a sign witnessed by the Meccans, then repeats the destruction of the peoples of Noah, 'Ad, Thamud, Lot, and Pharaoh with the refrain: 'We have made the Quran easy to remember — so is there any who will remember?'",
 themes:["Splitting of the moon","Quran made easy to remember"],
 virtue:"Its recurring refrain ('We have made the Quran easy to remember') is often cited as encouragement specifically for those working on memorization."},
{n:55,ar:"الرحمن",tr:"Ar-Rahman",en:"The Most Merciful",place:"Meccan",verses:78,
 summary:"Known as 'the Bride of the Quran,' it lists God's favors in creation with the recurring refrain 'so which of your Lord's favors will you both deny?' addressed to humankind and jinn together, describing both this world's bounty and Paradise's gardens.",
 themes:["God's favors","Paradise","Gratitude"],
 virtue:"Called 'the Bride of the Quran' in hadith; its rhythmic refrain makes it a popular surah for reflection on gratitude and for teaching children recitation."},
{n:56,ar:"الواقعة",tr:"Al-Waqi'ah",en:"The Inevitable Event",place:"Meccan",verses:96,
 summary:"Describes the Day of Judgment sorting people into three groups — the foremost, the companions of the right, and the companions of the left — with vivid, contrasting pictures of their rewards and punishments.",
 themes:["Three groups on Judgment Day","Reward & punishment"],
 virtue:"Widely recited for provision and protection from poverty, based on a hadith attributed to Imam Ali; many recite it nightly for this reason, though its authenticity is debated among scholars."},
{n:57,ar:"الحديد",tr:"Al-Hadid",en:"The Iron",place:"Medinan",verses:29,
 summary:"Calls believers to spend generously and reflect on the fleeting nature of worldly life, referencing iron as a resource of 'great strength and benefit for people' sent down alongside clear revelation and the balance of justice.",
 themes:["Charity","Impermanence of this world","Justice"]},
{n:58,ar:"المجادلة",tr:"Al-Mujadilah",en:"The Pleading Woman",place:"Medinan",verses:22,
 summary:"Opens by describing God hearing the plea of a woman disputing with the Prophet over an unjust pre-Islamic divorce custom (zihar), which the surah then abolishes and replaces with a just ruling.",
 themes:["Women's rights","God hears every plea"]},
{n:59,ar:"الحشر",tr:"Al-Hashr",en:"The Exile",place:"Medinan",verses:24,
 summary:"Describes the expulsion of the Banu Nadir tribe from Medina for treaty-breaking, and closes with a majestic description of God's names — the Sovereign, the Holy, the Source of Peace — among the most recited verses for God's attributes.",
 themes:["Treaty-breaking","Names of God"],
 virtue:"Its final three verses (59:22-24), a dense list of divine names, are widely recited in the morning for protection and blessing."},
{n:60,ar:"الممتحنة",tr:"Al-Mumtahanah",en:"She That Is to Be Examined",place:"Medinan",verses:13,
 summary:"Sets out how to treat family members and former enemies fairly even amid conflict, and lays down how women migrating to Medina were to be examined and welcomed into the community.",
 themes:["Fair treatment of enemies","Migration"]},
{n:61,ar:"الصف",tr:"As-Saff",en:"The Ranks",place:"Medinan",verses:14,
 summary:"Urges believers not to say what they do not do, praises those who fight for God's cause 'in ranks as if a solid structure,' and mentions Jesus foretelling a messenger to come after him named Ahmad.",
 themes:["Integrity","Unity","Jesus's prophecy"]},
{n:62,ar:"الجمعة",tr:"Al-Jumu'ah",en:"Friday",place:"Medinan",verses:11,
 summary:"Establishes the Friday congregational prayer, instructing believers to leave off business and 'hasten to the remembrance of God' when the call is made, then return to their affairs afterward.",
 themes:["Friday prayer","Balance of worship and work"],
 virtue:"Traditionally recited in the Friday congregational prayer itself, alongside Surah Al-Munafiqun."},
{n:63,ar:"المنافقون",tr:"Al-Munafiqun",en:"The Hypocrites",place:"Medinan",verses:11,
 summary:"Exposes the gap between the hypocrites' outward professions of faith and their inner disbelief, warning that their impressive appearance and speech hide hearts sealed against truth.",
 themes:["Hypocrisy","Sincerity of faith"]},
{n:64,ar:"التغابن",tr:"At-Taghabun",en:"Mutual Loss and Gain",place:"Medinan",verses:18,
 summary:"Describes Judgment Day as a day of 'mutual loss and gain' when true winners and losers are revealed, and encourages believers to trust God, spend in charity, and remain patient through family trials.",
 themes:["Judgment Day","Family trials","Trust in God"]},
{n:65,ar:"الطلاق",tr:"At-Talaq",en:"Divorce",place:"Medinan",verses:12,
 summary:"Lays out the waiting period, fair treatment, and financial responsibilities involved in divorce, repeating the assurance that 'whoever relies upon God — He is sufficient for him.'",
 themes:["Divorce law","Trust in God's sufficiency"]},
{n:66,ar:"التحريم",tr:"At-Tahrim",en:"The Prohibition",place:"Medinan",verses:12,
 summary:"Addresses a household matter involving the Prophet's wives, then draws a broader lesson using the wife of Noah and the wife of Lot (who disbelieved despite righteous husbands) against the wife of Pharaoh and Mary (who believed despite difficult circumstances).",
 themes:["Household matters","Faith independent of circumstance"]},
{n:67,ar:"الملك",tr:"Al-Mulk",en:"The Sovereignty",place:"Meccan",verses:30,
 summary:"Opens by declaring God's absolute sovereignty over life and death as a test of who does best in deeds, and describes the layered, faultless design of the seven heavens. Traditionally recommended for nightly recitation.",
 themes:["God's sovereignty","Design of creation"],
 virtue:"Widely recited before sleep every night; hadith describe it as intercession for its reciter and protection in the grave."},
{n:68,ar:"القلم",tr:"Al-Qalam",en:"The Pen",place:"Meccan",verses:52,
 summary:"Swears by the pen and what is written to defend the Prophet's character against accusations of madness, tells the parable of ungrateful garden owners who lost their harvest, and recalls Jonah's impatience as a caution.",
 themes:["The Prophet's character","Gratitude","Patience"]},
{n:69,ar:"الحاقة",tr:"Al-Haqqah",en:"The Reality",place:"Meccan",verses:52,
 summary:"Describes the 'Inevitable Reality' — the Day of Judgment — with the destruction of 'Ad and Thamud, and the moment people receive their record of deeds in their right or left hand as proof of the truth of revelation.",
 themes:["Judgment Day","Record of deeds"]},
{n:70,ar:"المعارج",tr:"Al-Ma'arij",en:"The Ascending Stairways",place:"Meccan",verses:44,
 summary:"Describes a day 'the length of fifty thousand years' ascending to God, contrasts the impatient, stingy nature of humans with the humility and steadfastness of true believers in prayer and charity.",
 themes:["Human impatience","Steadfastness in prayer"]},
{n:71,ar:"نوح",tr:"Nuh",en:"Noah",place:"Meccan",verses:28,
 summary:"Gives Noah's own account of nearly a millennium spent calling his people to God night and day, their persistent refusal, and his prayer that ultimately brought the Flood upon them.",
 themes:["Noah's patience","Persistent da'wah"],
 virtue:"Contains the verses (71:10-12) on the benefits of istighfar — increased provision, wealth, and children — frequently cited whenever the virtues of seeking forgiveness are taught."},
{n:72,ar:"الجن",tr:"Al-Jinn",en:"The Jinn",place:"Meccan",verses:28,
 summary:"Recounts a group of jinn who overheard the Quran being recited, were amazed by it, and returned to their own kind urging them to believe, affirming that both jinn and humans are addressed by revelation.",
 themes:["Jinn","Universal message of the Quran"]},
{n:73,ar:"المزمل",tr:"Al-Muzzammil",en:"The Enshrouded One",place:"Meccan",verses:20,
 summary:"Addresses the Prophet, wrapped in his cloak in the early days of revelation, instructing him in night prayer and patience as preparation for the 'weighty word' he was about to bear.",
 themes:["Night prayer","Preparation for hardship"]},
{n:74,ar:"المدثر",tr:"Al-Muddaththir",en:"The Cloaked One",place:"Meccan",verses:56,
 summary:"Among the earliest revelations, commanding the Prophet to 'arise and warn,' it also records the reasoning of a Meccan chief who dismissed the Quran as mere sorcery despite recognizing its power.",
 themes:["Call to action","Rejection of truth"]},
{n:75,ar:"القيامة",tr:"Al-Qiyamah",en:"The Resurrection",place:"Meccan",verses:40,
 summary:"Affirms bodily resurrection down to the fingertips being reassembled, describes the moment of death when the soul reaches the throat, and the disoriented rush of a person 'to your Lord that Day is the driving.'",
 themes:["Bodily resurrection","Moment of death"]},
{n:76,ar:"الإنسان",tr:"Al-Insan",en:"Man",place:"Medinan",verses:31,
 summary:"Also called Ad-Dahr ('Time'), it opens reflecting on humanity's humble origin and describes the reward of the truly righteous who give food to the needy, the orphan, and the captive 'out of love for Him,' saying only 'we feed you for the sake of God alone.'",
 shia:"Shia exegetes report this surah, especially verses 8-9, was revealed about Ali, Fatimah, Hasan and Husayn, who fasted three days after a vow and gave away their only food each evening to a poor man, an orphan, and a captive — a narrative found in both Sunni and Shia commentary traditions.",
 themes:["Sincere charity","Ahl al-Bayt"],
 virtue:"Traditionally recited in the Fajr prayer on Fridays, paired with Surah As-Sajdah."},
{n:77,ar:"المرسلات",tr:"Al-Mursalat",en:"Those Sent Forth",place:"Meccan",verses:50,
 summary:"Swears by winds and angels 'sent forth' in succession, and repeats the refrain 'woe that Day to the deniers' after each description of Judgment Day and the destruction of earlier nations.",
 themes:["Judgment Day","Consequences of denial"]},
{n:78,ar:"النبأ",tr:"An-Naba",en:"The Announcement",place:"Meccan",verses:40,
 summary:"Opens asking about 'the great announcement' — resurrection — that people dispute over, then describes the earth, mountains, and sky as evidence of a purposeful Creator who will judge all.",
 themes:["Resurrection","Signs in creation"]},
{n:79,ar:"النازعات",tr:"An-Nazi'at",en:"Those Who Drag Forth",place:"Meccan",verses:46,
 summary:"Swears by angels who draw out souls at death, retells Moses's confrontation with Pharaoh's false claim of divinity, and warns that the Day of Judgment will feel, to those who witness it, like it lasted only an evening.",
 themes:["Angels of death","Moses & Pharaoh"]},
{n:80,ar:"عبس",tr:"Abasa",en:"He Frowned",place:"Meccan",verses:42,
 summary:"Gently corrects the Prophet for turning attention from a blind seeker of guidance toward wealthy Meccan leaders, a moment of humility that became a lasting lesson on valuing sincerity over status.",
 themes:["Humility","Valuing sincerity over status"]},
{n:81,ar:"التكوير",tr:"At-Takwir",en:"The Overthrowing",place:"Meccan",verses:29,
 summary:"Opens with a rapid series of cosmic upheavals — the sun folded up, stars falling, seas boiling over — depicting the world's end before affirming the Quran as revelation delivered by a trustworthy angel, not madness or poetry.",
 themes:["End of the world","Authenticity of revelation"]},
{n:82,ar:"الإنفطار",tr:"Al-Infitar",en:"The Cleaving",place:"Meccan",verses:19,
 summary:"Describes the sky splitting open and graves being overturned on Judgment Day, reminding each person that two recording angels, honorable and noble, record everything they do.",
 themes:["End of the world","Recording angels"]},
{n:83,ar:"المطففين",tr:"Al-Mutaffifin",en:"Those Who Give Less",place:"Meccan",verses:36,
 summary:"Condemns merchants who cheat in weight and measure, demanding full measure for others what one demands for oneself, and contrasts the fate of the wicked, whose deeds 'rust' their hearts, with the righteous drinking a sealed, pure wine in Paradise.",
 themes:["Fair dealing","Honesty in business"]},
{n:84,ar:"الإنشقاق",tr:"Al-Inshiqaq",en:"The Splitting Open",place:"Meccan",verses:25,
 summary:"Describes the sky splitting and the earth stretching out and casting off its contents, obedient to its Lord, and affirms that every human being is 'toiling toward your Lord' and will meet the result.",
 themes:["End of the world","Life as toil toward God"]},
{n:85,ar:"البروج",tr:"Al-Buruj",en:"The Constellations",place:"Meccan",verses:22,
 summary:"Recalls the 'People of the Ditch,' believers burned alive for their faith by a tyrant, honoring their steadfastness and assuring persecuted believers everywhere that God witnesses and will judge such cruelty.",
 themes:["Steadfastness under persecution","Divine witness"]},
{n:86,ar:"الطارق",tr:"At-Tariq",en:"The Nightcomer",place:"Meccan",verses:17,
 summary:"Swears by the star that pierces through darkness to affirm that 'every soul has a protector over it' recording its deeds, and that the One who created from a spurting fluid is fully able to resurrect.",
 themes:["Protection over every soul","Resurrection"]},
{n:87,ar:"الأعلى",tr:"Al-A'la",en:"The Most High",place:"Meccan",verses:19,
 summary:"Calls to glorify 'the name of your Lord, the Most High,' who creates and proportions all things, and reassures the Prophet that his teaching will be made easy, echoed in earlier scriptures of Abraham and Moses.",
 themes:["Glorifying God","Teaching made easy"],
 virtue:"One of the most frequently recited surahs in daily prayer due to its brevity and rhythmic glorification of God."},
{n:88,ar:"الغاشية",tr:"Al-Ghashiyah",en:"The Overwhelming Event",place:"Meccan",verses:26,
 summary:"Contrasts the exhausted, fire-facing people of Hell with the content, honored people of Paradise, then invites reflection on camels, sky, mountains, and earth as evidence for a Creator, closing with a reminder that the Prophet's task is only to remind.",
 themes:["Paradise & Hell contrasted","Signs in nature"]},
{n:89,ar:"الفجر",tr:"Al-Fajr",en:"The Dawn",place:"Meccan",verses:30,
 summary:"Swears by the dawn and ten nights (commonly understood as the first ten of Dhul-Hijjah), recalls the destruction of 'Ad, Thamud, and Pharaoh for arrogance, and addresses 'the reassured soul' invited to return to its Lord well-pleased.",
 themes:["The reassured soul","Arrogance & downfall"]},
{n:90,ar:"البلد",tr:"Al-Balad",en:"The City",place:"Meccan",verses:20,
 summary:"Swears by Mecca, 'this city,' describing human life as toil, then defines true righteousness as freeing captives, feeding the hungry orphan and the destitute, and being among those who urge patience and compassion.",
 themes:["Righteousness in action","Compassion"]},
{n:91,ar:"الشمس",tr:"Ash-Shams",en:"The Sun",place:"Meccan",verses:15,
 summary:"A chain of oaths by the sun, moon, day, night, sky, and earth culminates in the truth that the soul that purifies itself succeeds and the one that corrupts itself fails, illustrated by Thamud's hamstringing of Salih's she-camel.",
 themes:["Purifying the soul","Personal responsibility"]},
{n:92,ar:"الليل",tr:"Al-Layl",en:"The Night",place:"Meccan",verses:21,
 summary:"Swears by night and day to contrast two paths: the one who gives charity, fears God, and believes in goodness is eased toward ease, while the one who withholds and denies is eased toward hardship.",
 themes:["Generosity vs. stinginess","Two paths"]},
{n:93,ar:"الضحى",tr:"Ad-Duha",en:"The Morning Brightness",place:"Meccan",verses:11,
 summary:"Revealed to comfort the Prophet after revelation paused and some mocked him for it, reassuring him that his Lord had not abandoned him and that what comes after would be better than before.",
 themes:["Comfort in hardship","Hope"],
 virtue:"A source of comfort widely recited or reflected on during periods of spiritual doubt or feeling distant from God."},
{n:94,ar:"الشرح",tr:"Ash-Sharh",en:"The Relief",place:"Meccan",verses:8,
 summary:"Continues the comfort of the previous surah, reminding the Prophet that his burden was lifted, and famously promises: 'indeed, with hardship comes ease' — repeated for emphasis.",
 themes:["Relief after hardship"],
 virtue:"Its promise 'with hardship comes ease' (repeated twice) is one of the most quoted verses in the Quran for encouragement during difficulty."},
{n:95,ar:"التين",tr:"At-Tin",en:"The Fig",place:"Meccan",verses:8,
 summary:"Swears by the fig, the olive, Mount Sinai, and Mecca to affirm that humanity was created 'in the best of forms,' but can fall to the lowest of the low without faith and righteous deeds.",
 themes:["Human dignity","Faith & good deeds"]},
{n:96,ar:"العلق",tr:"Al-Alaq",en:"The Clot",place:"Meccan",verses:19,
 summary:"Its first five verses are the very first revelation given to the Prophet in the Cave of Hira, beginning 'Read, in the name of your Lord who created' — the origin point of the entire Quran.",
 themes:["First revelation","Knowledge & reading"],
 virtue:"Its opening word, 'Iqra' (Read), is often cited as the reason knowledge and literacy hold such a high place in Islamic tradition."},
{n:97,ar:"القدر",tr:"Al-Qadr",en:"The Night of Decree",place:"Meccan",verses:5,
 summary:"Describes Laylat al-Qadr, the night the Quran began its descent, as 'better than a thousand months,' when angels and the Spirit descend with permission for every affair, and peace prevails until dawn.",
 shia:"Shia theology reads the descent of angels 'with every matter' each year on this night as continuing evidence that a living, divinely-appointed authority (the Imam) exists to receive that decree, linking this surah closely to the doctrine of ongoing Imamate.",
 themes:["Laylat al-Qadr","Descent of the Quran"],
 virtue:"Central to worship in the last ten nights of Ramadan, when Laylat al-Qadr is sought — a night described as better than a thousand months of worship."},
{n:98,ar:"البينة",tr:"Al-Bayyinah",en:"The Clear Proof",place:"Medinan",verses:8,
 summary:"Addresses the People of the Book and polytheists who awaited a clear proof, describing sincere worship as 'the correct religion' and naming believers who do good as 'the best of creation.'",
 themes:["Sincere worship","Clear proof"]},
{n:99,ar:"الزلزلة",tr:"Az-Zalzalah",en:"The Earthquake",place:"Medinan",verses:8,
 summary:"Describes the earth's violent quaking on the Last Day as it gives up its secrets and testifies to what was done upon it, closing with the principle that even an atom's weight of good or evil will be seen.",
 themes:["Every deed matters","Earth as witness"],
 virtue:"Its closing principle — that even an atom's weight of good or evil is seen — is frequently quoted to encourage small, consistent good deeds."},
{n:100,ar:"العاديات",tr:"Al-Adiyat",en:"The Chargers",place:"Meccan",verses:11,
 summary:"Swears by galloping warhorses striking sparks at dawn to rebuke human ingratitude, describing how intense a person's love of wealth truly is, and that all that is in the graves will be brought out and hearts' secrets exposed.",
 themes:["Ingratitude","Love of wealth"]},
{n:101,ar:"القارعة",tr:"Al-Qari'ah",en:"The Calamity",place:"Meccan",verses:11,
 summary:"Describes the Striking Calamity — Judgment Day — when people are 'like moths scattered' and mountains 'like carded wool,' weighing each person's deeds to determine a pleasant life or a burning abyss.",
 themes:["Judgment Day","Weighing of deeds"]},
{n:102,ar:"التكاثر",tr:"At-Takathur",en:"Rivalry in Worldly Increase",place:"Meccan",verses:8,
 summary:"Warns that the competitive pursuit of wealth and numbers distracts people 'until they visit the graves,' and that everyone will be questioned about the pleasures they enjoyed.",
 themes:["Materialism","Accountability for blessings"]},
{n:103,ar:"العصر",tr:"Al-Asr",en:"Time",place:"Meccan",verses:3,
 summary:"One of the shortest surahs, swearing by time itself that humanity is in loss — except those who believe, do righteous deeds, and counsel each other to truth and to patience. Imam Shafi'i said this surah alone would suffice for people's guidance.",
 themes:["Time","Righteous deeds","Mutual counsel"],
 virtue:"A well-known saying holds that if people reflected on nothing but this surah, it would be enough guidance for them — praised for compressing the entire purpose of life into three verses."},
{n:104,ar:"الهمزة",tr:"Al-Humazah",en:"The Slanderer",place:"Meccan",verses:9,
 summary:"Condemns the habitual slanderer and backbiter who hoards wealth thinking it will make him immortal, describing the crushing fire of Hell prepared for such behavior.",
 themes:["Slander","Hoarding wealth"]},
{n:105,ar:"الفيل",tr:"Al-Fil",en:"The Elephant",place:"Meccan",verses:5,
 summary:"Recalls the year of the Prophet's birth, when Abraha's elephant-led army marched to destroy the Kaaba and was repelled by flocks of birds pelting them with stones, a well-known historical sign of divine protection over the sanctuary.",
 themes:["Historical sign","Protection of the Kaaba"]},
{n:106,ar:"قريش",tr:"Quraysh",en:"Quraysh",place:"Meccan",verses:4,
 summary:"Reminds the Quraysh tribe of Mecca to be grateful to the Lord of the Kaaba, who secured their winter and summer trade caravans and fed them from hunger and kept them safe from fear.",
 themes:["Gratitude","Security & provision"]},
{n:107,ar:"الماعون",tr:"Al-Ma'un",en:"Small Kindnesses",place:"Meccan",verses:7,
 summary:"Describes the one who denies faith as the one who mistreats orphans, does not urge feeding the poor, prays without sincerity, and withholds even small acts of assistance from neighbors.",
 themes:["Orphans","Sincerity in prayer","Small kindnesses"]},
{n:108,ar:"الكوثر",tr:"Al-Kawthar",en:"Abundance",place:"Meccan",verses:3,
 summary:"The shortest surah in the Quran, revealed to console the Prophet against those who mocked him as cut off from descendants, promising him 'al-Kawthar,' abundant good — traditionally understood to include a river in Paradise.",
 shia:"Shia commentators, citing the surah's revelation after Meccans taunted the Prophet for having no surviving sons, read 'abundance' as including his blessed lineage through his daughter Fatimah, from whom the eleven Imams and countless descendants trace their line — making this a surah honoring her.",
 themes:["Abundance","Fatimah's lineage"]},
{n:109,ar:"الكافرون",tr:"Al-Kafirun",en:"The Disbelievers",place:"Meccan",verses:6,
 summary:"A firm declaration of religious independence to those who proposed a compromise of shared worship: 'I do not worship what you worship... to you your religion, and to me my religion.'",
 themes:["Religious integrity","Clear boundaries"],
 virtue:"Paired with Al-Ikhlas as commonly recited surahs in the two units of the dawn (fajr) and post-obligatory prayers, for their clarity on tawhid and disbelief."},
{n:110,ar:"النصر",tr:"An-Nasr",en:"Divine Support",place:"Medinan",verses:3,
 summary:"Revealed near the end of the Prophet's life, announcing God's help, the conquest of Mecca, and people entering the religion 'in multitudes,' instructing the Prophet to glorify God and seek forgiveness — read by many as a gentle sign of his approaching death.",
 themes:["Victory","Glorification & forgiveness"]},
{n:111,ar:"المسد",tr:"Al-Masad",en:"The Palm Fiber",place:"Meccan",verses:5,
 summary:"Condemns Abu Lahab, the Prophet's uncle and fierce opponent, and his wife, for their active hostility to the message — the only surah naming a specific individual for such rebuke.",
 themes:["Opposition to the Prophet","Consequences of enmity"]},
{n:112,ar:"الإخلاص",tr:"Al-Ikhlas",en:"Sincerity",place:"Meccan",verses:4,
 summary:"A concise creed of pure monotheism — 'Say: He is God, One; God, the Eternal Refuge; He neither begets nor is born; nor is there to Him any equivalent' — described by the Prophet as equal to one-third of the Quran in meaning.",
 themes:["Tawhid","Concise creed"],
 virtue:"Described by the Prophet as equal to one-third of the Quran in meaning; one of the most memorized surahs, often a child's first after Al-Fatiha."},
{n:113,ar:"الفلق",tr:"Al-Falaq",en:"The Daybreak",place:"Meccan",verses:5,
 summary:"A short protective prayer seeking refuge in God, Lord of the daybreak, from the evil of what He created, the darkness of night, sorcery, and envy.",
 themes:["Protection","Refuge from harm"],
 virtue:"Recited together with An-Nas (the 'Mu'awwidhatayn') for protection, especially before sleep and after each obligatory prayer."},
{n:114,ar:"الناس",tr:"An-Nas",en:"Mankind",place:"Meccan",verses:6,
 summary:"The Quran's closing surah, seeking refuge in God, Lord and King of mankind, from the whispering of the retreating whisperer (Satan) who whispers into people's hearts — paired with Al-Falaq as the two protective 'Mu'awwidhatayn.'",
 themes:["Protection from whispers","Closing surah"],
 virtue:"Recited together with Al-Falaq for protection; many recite both three times each morning and evening, and before sleep, following the Prophet's practice."}
];

if (typeof module !== "undefined") module.exports = { SURAHS };
