/* ===================================================================
   Quran & Me — Core vocabulary glossary
   ~120 of the most frequent / theologically central Arabic words in
   the Quran, with root, plain meaning, and one example reference.
   Categories used for browsing: worship, belief, character, law,
   hereafter, prophets, family, nature.
   =================================================================== */

const VOCAB = [
{ar:"الله",tr:"Allah",meaning:"God — the single proper name for the one Creator, used by Arabic-speaking Jews, Christians and Muslims alike.",cat:"belief",ref:"1:1"},
{ar:"رب",tr:"Rabb",meaning:"Lord, Sustainer, Cherisher — the One who nurtures and brings things to their perfection, not merely 'master.'",cat:"belief",ref:"1:2"},
{ar:"الرحمن",tr:"Ar-Rahman",meaning:"The Most Merciful — mercy that encompasses all creation, believer and disbeliever alike.",cat:"belief",ref:"1:1"},
{ar:"الرحيم",tr:"Ar-Rahim",meaning:"The Especially Merciful — mercy shown particularly to believers, in this life and the next.",cat:"belief",ref:"1:1"},
{ar:"دين",tr:"Deen",meaning:"Way of life, religion, and also 'judgment' — Islam is described as a complete deen, not only ritual.",cat:"belief",ref:"1:4"},
{ar:"توحيد",tr:"Tawhid",meaning:"The oneness of God — the central doctrine that God has no partner, equal, or division.",cat:"belief",ref:"112:1"},
{ar:"شرك",tr:"Shirk",meaning:"Associating partners with God — considered the gravest wrong in the Quran.",cat:"belief",ref:"31:13"},
{ar:"كفر",tr:"Kufr",meaning:"Disbelief, or covering up known truth — the root also means 'to cover,' as a farmer covers a seed.",cat:"belief",ref:"2:6"},
{ar:"إيمان",tr:"Iman",meaning:"Faith — inner conviction affirmed by the heart, expressed by the tongue and acted upon by the limbs.",cat:"belief",ref:"49:14"},
{ar:"إسلام",tr:"Islam",meaning:"Submission to God — willing surrender of oneself to God's will and guidance.",cat:"belief",ref:"3:19"},
{ar:"تقوى",tr:"Taqwa",meaning:"God-consciousness, mindful piety — living as if shielding oneself from God's displeasure in every choice.",cat:"character",ref:"2:2"},
{ar:"صبر",tr:"Sabr",meaning:"Patience, perseverance — steadfast endurance through hardship without complaint against God.",cat:"character",ref:"2:153"},
{ar:"شكر",tr:"Shukr",meaning:"Gratitude — acknowledging blessings and using them as God intended.",cat:"character",ref:"14:7"},
{ar:"توكل",tr:"Tawakkul",meaning:"Reliance on God — trusting God's plan after doing one's own reasonable effort.",cat:"character",ref:"65:3"},
{ar:"إخلاص",tr:"Ikhlas",meaning:"Sincerity — doing deeds purely for God, free of showing off or seeking praise.",cat:"character",ref:"98:5"},
{ar:"خشوع",tr:"Khushu'",meaning:"Humble attentiveness, especially in prayer — a settled, reverent heart.",cat:"character",ref:"23:2"},
{ar:"صدق",tr:"Sidq",meaning:"Truthfulness — honesty in word, promise, and inner intention.",cat:"character",ref:"33:35"},
{ar:"عدل",tr:"'Adl",meaning:"Justice — giving each person and situation exactly its due.",cat:"character",ref:"16:90"},
{ar:"إحسان",tr:"Ihsan",meaning:"Excellence, doing good beautifully — worshipping God as though you see Him, and treating others with the best conduct.",cat:"character",ref:"16:90"},
{ar:"رحمة",tr:"Rahmah",meaning:"Mercy, compassion — the quality most repeated as a divine attribute in the Quran.",cat:"character",ref:"7:156"},
{ar:"حكمة",tr:"Hikmah",meaning:"Wisdom — sound judgment that places things and actions in their right place.",cat:"character",ref:"2:269"},
{ar:"صلاة",tr:"Salah",meaning:"The ritual prayer performed five times daily, the second pillar of practice.",cat:"worship",ref:"2:238"},
{ar:"زكاة",tr:"Zakah",meaning:"Obligatory almsgiving that purifies wealth — literally 'that which purifies and causes growth.'",cat:"worship",ref:"9:103"},
{ar:"صوم",tr:"Sawm",meaning:"Fasting, especially the obligatory fast of Ramadan from dawn to sunset.",cat:"worship",ref:"2:183"},
{ar:"حج",tr:"Hajj",meaning:"The pilgrimage to the Kaaba in Mecca, obligatory once in a lifetime for those able.",cat:"worship",ref:"3:97"},
{ar:"دعاء",tr:"Du'a",meaning:"Supplication — calling upon God directly with one's needs and hopes.",cat:"worship",ref:"40:60"},
{ar:"ذكر",tr:"Dhikr",meaning:"Remembrance of God — through recitation, praise, or quiet inner awareness.",cat:"worship",ref:"13:28"},
{ar:"تلاوة",tr:"Tilawah",meaning:"Recitation of the Quran, especially with reflection on its meaning.",cat:"worship",ref:"35:29"},
{ar:"سجدة",tr:"Sajdah",meaning:"Prostration — placing the forehead on the ground, the position of deepest submission in prayer.",cat:"worship",ref:"32:15"},
{ar:"توبة",tr:"Tawbah",meaning:"Repentance — turning back to God after sin, with regret and resolve not to return to it.",cat:"worship",ref:"66:8"},
{ar:"استغفار",tr:"Istighfar",meaning:"Seeking God's forgiveness, typically by saying 'astaghfirullah.'",cat:"worship",ref:"11:3"},
{ar:"آخرة",tr:"Akhirah",meaning:"The Hereafter — the eternal life after resurrection, contrasted with the temporary dunya (this world).",cat:"hereafter",ref:"2:4"},
{ar:"دنيا",tr:"Dunya",meaning:"This worldly life — literally 'the nearer' life, temporary and a test.",cat:"hereafter",ref:"57:20"},
{ar:"قيامة",tr:"Qiyamah",meaning:"The Resurrection — when all people are raised for judgment.",cat:"hereafter",ref:"75:1"},
{ar:"جنة",tr:"Jannah",meaning:"Paradise, literally 'garden' — the eternal reward of the righteous.",cat:"hereafter",ref:"3:133"},
{ar:"جهنم",tr:"Jahannam",meaning:"Hell — the place of punishment for persistent wrongdoing and disbelief.",cat:"hereafter",ref:"15:43"},
{ar:"ميزان",tr:"Mizan",meaning:"The Balance — the just weighing of every deed on Judgment Day.",cat:"hereafter",ref:"21:47"},
{ar:"حساب",tr:"Hisab",meaning:"The Reckoning — the detailed accounting of a person's deeds before God.",cat:"hereafter",ref:"84:8"},
{ar:"صراط",tr:"Sirat",meaning:"The Path — both the 'straight path' of guidance in this life and, in tradition, a bridge over Hell in the next.",cat:"hereafter",ref:"1:6"},
{ar:"شفاعة",tr:"Shafa'ah",meaning:"Intercession — pleading on another's behalf before God, granted only by His permission.",cat:"hereafter",ref:"2:255"},
{ar:"نبي",tr:"Nabi",meaning:"Prophet — one who receives revelation from God.",cat:"prophets",ref:"33:40"},
{ar:"رسول",tr:"Rasul",meaning:"Messenger — a prophet sent with a scripture or law for their people.",cat:"prophets",ref:"33:40"},
{ar:"وحي",tr:"Wahy",meaning:"Revelation — divine communication given to prophets.",cat:"prophets",ref:"42:51"},
{ar:"كتاب",tr:"Kitab",meaning:"Book / Scripture — used for the Quran and earlier revealed books alike.",cat:"prophets",ref:"2:2"},
{ar:"آية",tr:"Ayah",meaning:"A sign or verse — both a verse of the Quran and any sign in creation pointing to God.",cat:"prophets",ref:"41:53"},
{ar:"سورة",tr:"Surah",meaning:"A chapter of the Quran; there are 114 in total.",cat:"prophets",ref:"2:23"},
{ar:"ملاك",tr:"Malak (pl. Mala'ikah)",meaning:"Angel — created beings of light who obey God without fail and carry out His commands.",cat:"belief",ref:"35:1"},
{ar:"جن",tr:"Jinn",meaning:"Beings created from smokeless fire, given free will like humans, who can believe or disbelieve.",cat:"belief",ref:"51:56"},
{ar:"شيطان",tr:"Shaytan",meaning:"Satan / a devil — a being (jinn, in Iblis's case) that whispers temptation to sin.",cat:"belief",ref:"114:4"},
{ar:"ولاية / ولي",tr:"Wilayah / Wali",meaning:"Guardianship, authority, and closeness — in Shia theology, the spiritual and political authority of the Prophet and the Imams after him.",cat:"belief",ref:"5:55"},
{ar:"إمام",tr:"Imam",meaning:"Leader — in Shia belief, the divinely appointed, infallible successors to the Prophet from the Ahl al-Bayt who guide the community after him.",cat:"belief",ref:"2:124"},
{ar:"أهل البيت",tr:"Ahl al-Bayt",meaning:"'The People of the House' — the Prophet's family, especially Ali, Fatimah, Hasan, and Husayn, named in the Verse of Purification (33:33).",cat:"family",ref:"33:33"},
{ar:"عصمة",tr:"'Ismah",meaning:"Infallibility — protection from sin and error, believed in Shia theology to be granted to prophets and Imams.",cat:"belief",ref:"33:33"},
{ar:"شفاعة أهل البيت",tr:"Mawaddah",meaning:"Love and affection — specifically the love for the Prophet's near relatives commanded in 42:23.",cat:"family",ref:"42:23"},
{ar:"غيب",tr:"Ghayb",meaning:"The unseen — realities beyond human perception, knowledge of which belongs fully to God.",cat:"belief",ref:"2:3"},
{ar:"فطرة",tr:"Fitrah",meaning:"The innate, God-given disposition every human is born with, inclined toward recognizing God.",cat:"belief",ref:"30:30"},
{ar:"نفس",tr:"Nafs",meaning:"Soul or self — the Quran describes stages: the commanding self (ammarah), the self-reproaching self (lawwamah), and the tranquil self (mutma'innah).",cat:"character",ref:"89:27"},
{ar:"قلب",tr:"Qalb",meaning:"Heart — the seat of understanding, intention, and spiritual perception, which can be sealed or opened.",cat:"character",ref:"22:46"},
{ar:"عقل",tr:"'Aql",meaning:"Reason, intellect — repeatedly invoked in the Quran as a faculty for recognizing truth.",cat:"character",ref:"2:164"},
{ar:"علم",tr:"'Ilm",meaning:"Knowledge — highly praised in the Quran; the first revealed word command was 'Read.'",cat:"character",ref:"96:1"},
{ar:"حق",tr:"Haqq",meaning:"Truth, or a rightful due — also one of God's names, Al-Haqq, 'the Truth.'",cat:"character",ref:"17:81"},
{ar:"باطل",tr:"Batil",meaning:"Falsehood — that which has no lasting reality or worth, contrasted with al-Haqq.",cat:"character",ref:"17:81"},
{ar:"ظلم",tr:"Zulm",meaning:"Wrongdoing, oppression — literally 'placing something out of its proper place.'",cat:"character",ref:"31:13"},
{ar:"فسق",tr:"Fisq",meaning:"Defiant disobedience — stepping outside the bounds of God's command knowingly.",cat:"character",ref:"49:11"},
{ar:"نفاق",tr:"Nifaq",meaning:"Hypocrisy — outwardly professing faith while inwardly disbelieving or being insincere.",cat:"character",ref:"63:1"},
{ar:"كبر",tr:"Kibr",meaning:"Arrogance, pride — the sin that caused Iblis to refuse to bow to Adam.",cat:"character",ref:"7:13"},
{ar:"حسد",tr:"Hasad",meaning:"Envy — wishing another person's blessing were taken away.",cat:"character",ref:"113:5"},
{ar:"صراط مستقيم",tr:"Sirat al-Mustaqim",meaning:"The Straight Path — the way of guidance asked for in every unit of prayer.",cat:"belief",ref:"1:6"},
{ar:"هدى",tr:"Huda",meaning:"Guidance — divine direction toward what is true and beneficial.",cat:"belief",ref:"2:2"},
{ar:"ضلال",tr:"Dalal",meaning:"Misguidance, straying from the right way.",cat:"belief",ref:"1:7"},
{ar:"نور",tr:"Nur",meaning:"Light — used for divine guidance and for God's own attribute as 'the Light of the heavens and the earth' (24:35).",cat:"belief",ref:"24:35"},
{ar:"ظلمات",tr:"Dhulumat",meaning:"Darknesses — the Quran repeatedly moves people 'from darknesses into the light.'",cat:"belief",ref:"2:257"},
{ar:"أمانة",tr:"Amanah",meaning:"Trust — moral responsibility that the heavens, earth and mountains declined but humanity accepted.",cat:"character",ref:"33:72"},
{ar:"ميثاق",tr:"Mithaq",meaning:"Covenant — a solemn pact, including the primordial covenant every soul made affirming God's lordship.",cat:"belief",ref:"7:172"},
{ar:"بينة",tr:"Bayyinah",meaning:"Clear proof or evidence — used for miracles and for unambiguous revealed teaching.",cat:"belief",ref:"98:1"},
{ar:"معجزة",tr:"Mu'jizah",meaning:"Miracle — a sign given to a prophet that others are unable to replicate.",cat:"prophets",ref:"2:23"},
{ar:"أمة",tr:"Ummah",meaning:"Community or nation — used both for the global Muslim community and for any people to whom a messenger was sent.",cat:"family",ref:"2:143"},
{ar:"قوم",tr:"Qawm",meaning:"A people or nation, often referring to a prophet's own community who accepted or rejected him.",cat:"prophets",ref:"7:59"},
{ar:"بر",tr:"Birr",meaning:"Righteousness, goodness, especially dutifulness to parents.",cat:"character",ref:"2:177"},
{ar:"إحسان الوالدين",tr:"Birr al-Walidayn",meaning:"Kindness and dutifulness to one's parents, commanded directly after worshipping God alone in several verses.",cat:"family",ref:"17:23"},
{ar:"صلة الرحم",tr:"Silat al-Rahim",meaning:"Maintaining family ties — keeping connection and kindness with relatives.",cat:"family",ref:"4:1"},
{ar:"يتيم",tr:"Yatim",meaning:"Orphan — a child who has lost their father; the Quran repeatedly commands their protection and fair treatment.",cat:"family",ref:"93:9"},
{ar:"مسكين",tr:"Miskin",meaning:"The poor, needy person — one lacking sufficient means, deserving charity.",cat:"family",ref:"107:3"},
{ar:"صدقة",tr:"Sadaqah",meaning:"Voluntary charity given out of sincerity, beyond the obligatory zakah.",cat:"worship",ref:"2:271"},
{ar:"ربا",tr:"Riba",meaning:"Usury / interest — exploitative gain forbidden in the Quran as unjust to the vulnerable.",cat:"law",ref:"2:275"},
{ar:"حلال",tr:"Halal",meaning:"Permissible, lawful according to divine guidance.",cat:"law",ref:"5:88"},
{ar:"حرام",tr:"Haram",meaning:"Forbidden, unlawful according to divine guidance.",cat:"law",ref:"5:87"},
{ar:"شريعة",tr:"Shari'ah",meaning:"The revealed law and path of religious practice.",cat:"law",ref:"45:18"},
{ar:"ميثاق النكاح",tr:"Mithaqan Ghalizan",meaning:"'A solemn covenant' — how the Quran describes the marriage bond.",cat:"family",ref:"4:21"},
{ar:"طلاق",tr:"Talaq",meaning:"Divorce — permitted but discouraged, hedged with waiting periods and fairness requirements.",cat:"law",ref:"65:1"},
{ar:"ميراث",tr:"Mirath",meaning:"Inheritance — the Quran fixes detailed shares for family members, an early legal reform protecting women's and orphans' rights.",cat:"law",ref:"4:11"},
{ar:"شهادة",tr:"Shahadah",meaning:"Testimony or witness — both legal witnessing and the declaration of faith.",cat:"worship",ref:"2:282"},
{ar:"جهاد",tr:"Jihad",meaning:"Struggle or striving — encompassing inner moral striving, and, under strict conditions, defensive struggle for a just cause.",cat:"character",ref:"29:69"},
{ar:"صراع الخير والشر",tr:"Fitnah",meaning:"Trial, temptation, or civil discord — testing that reveals the true state of a person's faith.",cat:"belief",ref:"29:2"},
{ar:"بلاء",tr:"Bala'",meaning:"Test or trial — hardship or ease used by God to distinguish sincere believers.",cat:"belief",ref:"21:35"},
{ar:"أجر",tr:"Ajr",meaning:"Reward — the recompense promised by God for sincere good deeds.",cat:"hereafter",ref:"18:30"},
{ar:"عمل صالح",tr:"'Amal Salih",meaning:"Righteous deeds — the practical expression of faith the Quran always pairs with belief.",cat:"character",ref:"103:3"},
{ar:"موت",tr:"Mawt",meaning:"Death — described as a certainty every soul will taste before returning to God.",cat:"hereafter",ref:"3:185"},
{ar:"روح",tr:"Ruh",meaning:"Spirit — breathed by God into Adam, and also a title for the angel Gabriel ('the Trustworthy Spirit').",cat:"belief",ref:"15:29"},
{ar:"سماء",tr:"Sama'",meaning:"Sky / heaven(s) — used both for the physical sky and, in the plural, the seven layered heavens.",cat:"nature",ref:"41:12"},
{ar:"أرض",tr:"Ard",meaning:"Earth — repeatedly described as a resting place spread out for humanity.",cat:"nature",ref:"2:22"},
{ar:"خلق",tr:"Khalq",meaning:"Creation — the act of bringing something into being from nothing or from another form.",cat:"nature",ref:"7:54"},
{ar:"ماء",tr:"Ma'",meaning:"Water — the Quran states 'We made from water every living thing' (21:30).",cat:"nature",ref:"21:30"},
{ar:"شجرة",tr:"Shajarah",meaning:"Tree — used literally and as a metaphor, such as the 'good word' likened to a firmly rooted tree (14:24).",cat:"nature",ref:"14:24"},
{ar:"جبل",tr:"Jabal",meaning:"Mountain — described as 'pegs' stabilizing the earth.",cat:"nature",ref:"78:7"},
{ar:"بحر",tr:"Bahr",meaning:"Sea — invoked as a sign of God's power and provision, and the setting of Moses's parting of the waters.",cat:"nature",ref:"26:63"},
{ar:"شمس",tr:"Shams",meaning:"Sun — one of the great cosmic signs sworn by in Surah Ash-Shams.",cat:"nature",ref:"91:1"},
{ar:"قمر",tr:"Qamar",meaning:"Moon — its phases mark time; its splitting is referenced as a sign in Surah Al-Qamar.",cat:"nature",ref:"54:1"},
{ar:"نجم",tr:"Najm",meaning:"Star — set in the sky as decoration and, traditionally, as a means of navigation.",cat:"nature",ref:"16:16"},
{ar:"ملك",tr:"Mulk",meaning:"Sovereignty, dominion — belonging absolutely to God over all creation.",cat:"belief",ref:"67:1"},
{ar:"عرش",tr:"'Arsh",meaning:"The Throne — a symbol of God's total authority, which His knowledge and power encompass entirely.",cat:"belief",ref:"2:255"},
{ar:"كرسي",tr:"Kursi",meaning:"The Footstool — mentioned in Ayat al-Kursi (2:255) as extending over the heavens and the earth.",cat:"belief",ref:"2:255"},
{ar:"وحدانية",tr:"Wahdaniyyah",meaning:"Divine Oneness — the state of God being singularly and indivisibly one.",cat:"belief",ref:"112:1"},
{ar:"استقامة",tr:"Istiqamah",meaning:"Steadfastness — staying firmly on the straight path once guided to it.",cat:"character",ref:"46:13"},
{ar:"يقين",tr:"Yaqin",meaning:"Certainty — the firmest, most settled level of conviction in faith.",cat:"belief",ref:"15:99"},
{ar:"خشية",tr:"Khashyah",meaning:"Awe mixed with reverent fear of God, rooted in recognizing His greatness.",cat:"character",ref:"35:28"},
{ar:"محبة",tr:"Mahabbah",meaning:"Love — especially love of God as the highest motivation for worship and obedience.",cat:"character",ref:"2:165"},
{ar:"تفكر",tr:"Tafakkur",meaning:"Reflection, contemplation — the Quran repeatedly invites 'those who reflect' to consider its signs.",cat:"character",ref:"3:191"},
{ar:"تدبر",tr:"Tadabbur",meaning:"Deep contemplation of the Quran's meanings, going beyond surface recitation.",cat:"worship",ref:"38:29"},
{ar:"وحدة",tr:"Wahdah",meaning:"Unity — the Quran repeatedly calls believers to 'hold firmly to the rope of God together and do not become divided' (3:103).",cat:"family",ref:"3:103"}
];

if (typeof module !== "undefined") module.exports = { VOCAB };
